name: linh-bay-workflow-sample

on:
  push:
    branches:
      - "staging"

jobs:
  build-something-meaningful:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
